DROP TABLE if exists rutas,
roles,
rutasroles,
instituciones,
grados,
usuarios,
instituciones,
profesoresencargados,
niveles,
preguntas,
opcionespreguntas,
imagenespreguntas,
pruebas,
preguntaspruebas,
puntajepruebas